2025-04-08 16:54:07,980 [main.py         | 28] INFO: Start to run instance_1
2025-04-08 16:54:07,981 [simulate_api.py | 60] INFO: Start time of the simulator: 2025-04-08 00:00:00, time interval:  600.00
2025-04-08 16:54:07,988 [input_utils.py  | 28] INFO: Get 154 factories
2025-04-08 16:54:08,767 [input_utils.py  | 32] INFO: Get 23562 routes
2025-04-08 16:54:08,778 [input_utils.py  | 37] INFO: Get 5 vehicles
2025-04-08 16:54:08,785 [input_utils.py  | 41] INFO: Get 50 orders
2025-04-08 16:54:08,785 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2025-04-08 16:54:08,786 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2025-04-08 16:54:08,786 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2025-04-08 16:54:08,786 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2025-04-08 16:54:08,786 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2025-04-08 16:54:08,786 [simulate_environment.py | 99] INFO: **************************************************
2025-04-08 16:54:08,786 [simulate_environment.py | 103] INFO: cur time: 2025-04-08 00:10:00, pre time: 2025-04-08 00:00:00
2025-04-08 16:54:08,786 [simulate_environment.py | 140] INFO: Start to update the input of 2025-04-08 00:10:00
2025-04-08 16:54:08,787 [simulate_environment.py | 167] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2025-04-08 16:54:10,085 [simulate_environment.py | 232] INFO: Cant initialize the population


V_1:[] V_2:[] V_3:[] V_4:[] V_5:[p1_0003480001-1 d1_0003480001-1]
V_1:[] V_2:[] V_3:[] V_4:[] V_5:[p1_0003480001-1 d1_0003480001-1]
After GA, the cost of solution decrease from 3.08 to 3.08
SUCCESS

2025-04-08 16:54:10,094 [simulate_environment.py | 254] INFO: 2025-04-08 00:10:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2025-04-08 16:54:10,094 [simulate_environment.py | 99] INFO: **************************************************
2025-04-08 16:54:10,094 [simulate_environment.py | 103] INFO: cur time: 2025-04-08 00:20:00, pre time: 2025-04-08 00:10:00
2025-04-08 16:54:10,094 [simulate_environment.py | 140] INFO: Start to update the input of 2025-04-08 00:20:00
2025-04-08 16:54:10,098 [simulate_environment.py | 167] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2025-04-08 16:54:11,339 [simulate_environment.py | 232] INFO: 
2
V_1:[] V_2:[] V_3:[] V_4:[] V_5:[p1_0003480001-1 d1_0003480001-1]
2025-04-08 16:54:11,291 [main_algorithm.py | 11] ERROR: Failed to run algorithm
2025-04-08 16:54:11,293 [main_algorithm.py | 12] ERROR: Error: select_parents() missing 1 required positional argument: 'idx', Traceback (most recent call last):
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\main_algorithm.py", line 8, in <module>
    main()
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\algorithm\main.py", line 624, in main
    best_chromosome =  CCEA(initial_chromosome)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\algorithm\CCEA.py", line 42, in CCEA
    parent1, parent2 = select_parents(P)
                       ^^^^^^^^^^^^^^^^^
TypeError: select_parents() missing 1 required positional argument: 'idx'

FAIL

2025-04-08 16:54:11,339 [simulate_environment.py | 246] ERROR: 
2
V_1:[] V_2:[] V_3:[] V_4:[] V_5:[p1_0003480001-1 d1_0003480001-1]
2025-04-08 16:54:11,291 [main_algorithm.py | 11] ERROR: Failed to run algorithm
2025-04-08 16:54:11,293 [main_algorithm.py | 12] ERROR: Error: select_parents() missing 1 required positional argument: 'idx', Traceback (most recent call last):
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\main_algorithm.py", line 8, in <module>
    main()
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\algorithm\main.py", line 624, in main
    best_chromosome =  CCEA(initial_chromosome)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PHUC\DPDP\Dynamic-Pickup--and-Delivery-Problem\algorithm\CCEA.py", line 42, in CCEA
    parent1, parent2 = select_parents(P)
                       ^^^^^^^^^^^^^^^^^
TypeError: select_parents() missing 1 required positional argument: 'idx'

FAIL

2025-04-08 16:54:11,340 [simulate_environment.py | 247] ERROR: Can not catch the 'SUCCESS' from the algorithm. 未寻获算法输出成功标识'SUCCESS'。
